export const reasons = [
    "❌ Wrong pick",
    "📖 Misread it",
    "🔍 Almost there",
    "⏳ Time ran out",
    "🤦 Silly mistake",
    "🎯 Tricky Question",
    "⏱️ Last-Second Error",
    "🔄 Overthought it",
    "😵‍💫 Lost focus",
    "🧊 Brain freeze",
    "🖱️ Misclicked",
    "🧩 Confused Logic",
    "🕵️ Missed clue",
    "🚫 Wrong approach",
    "🔄 Lengthy approach",
    "📏 Wrong formula",
    "🤔 Forget formula",
    "🧠 Forget concept",
  ] as const;