export const reasons = [
  "🧠 Forgot Usage",
  "📝 Doable, Too Long",
  "❌ Wrong pick",
  "📖 Misread it",
  "🔍 Almost there",
  "⏳ Time Constraint",
  "🤦 Silly mistake",
  "🎯 Tricky Question",
  "⏱️ Time Overrun",
  "🔄 Overthought it",
  "😵‍💫 Lost focus",
  "🧊 Brain freeze",
  "🧩 Complex Question",
  "🕵️ Missed clue",
  "🚫 Wrong approach",
  "🔢 Heavy Calculation",
  "📏 Wrong formula",
  "🤔 Forgot Formula",
  "🧠 Forgot Concept",
  "🧐 Forgot Approach",
  "❓ Question not clear",
  "🦁 Wildcard",
  "✔️ Right Intuition",
  "❌ Calculation Error",
  "✅ Known Answer",
  "🔄 Re-evaluated",
  "💭 Took Too Long"
] as const;
